function FCExpression_PropertyTests(obj)
   NumberPropertyTest(obj, "FCExpression", "GraceNoteIndex", {0, 1, 2, 3, 4})
   NumberPropertyTest(obj, "FCExpression", "HorizontalPos", {-144, 0, 144})
   NumberPropertyTest(obj, "FCExpression", "ID", {1, 17})
   NumberPropertyTest(obj, "FCExpression", "LayerAssignment", {0, 1, 2, 3, 4})
   NumberPropertyTest_RO(obj, "FCExpression", "Measure", {0, 1, 2})
   NumberPropertyTest(obj, "FCExpression", "MeasurePos", {0, 1024, 255})
   BoolPropertyTest(obj, "FCExpression", "PartAssignment")
   NumberPropertyTest(obj, "FCExpression", "PlaybackLayerAssignment", {0, 1, 2, 3, 4, 5, 6})
   NumberPropertyTest(obj, "FCExpression", "PlaybackStart", {finale.EXPRPLAYSTART_ALIGNMENTPOINT, finale.EXPRPLAYSTART_BEGINNINGOFMEASURE, finale.EXPRPLAYSTART_POSINMEASURE})
   NumberPropertyTest(obj, "FCExpression", "RehearsalMarkOffset", {-144, 0, 144})
   BoolPropertyTest(obj, "FCExpression", "ScaleWithEntry")
   BoolPropertyTest(obj, "FCExpression", "ScoreAssignment")
   BoolPropertyTest(obj, "FCExpression", "Shape")
   NumberPropertyTest(obj, "FCExpression", "Staff", {0, 1, 12})
   NumberPropertyTest(obj, "FCExpression", "StaffGroupID", {0, 1, 17})
   NumberPropertyTest(obj, "FCExpression", "StaffListID", {0, 1, 13})
   BoolPropertyTest(obj, "FCExpression", "TracksVoice2")
   NumberPropertyTest(obj, "FCExpression", "VerticalPos", {-144, 0, 144})
   BoolPropertyTest(obj, "FCExpression", "Visible")
end


-- Call:
local expressions = finale.FCExpressions()
local result = expressions:LoadAllForItem(3)
AssureTrue(result >= 1, "FCExpressions:Load()")
local obj = expressions:GetItemAt(0)
FCExpression_PropertyTests(obj)
