function TestConstants_EXPRPLAYSTART_()
   NumberConstantTest(finale.EXPRPLAYSTART_ALIGNMENTPOINT, "EXPRPLAYSTART_ALIGNMENTPOINT", 1)
   NumberConstantTest(finale.EXPRPLAYSTART_BEGINNINGOFMEASURE, "EXPRPLAYSTART_BEGINNINGOFMEASURE", 2)
   NumberConstantTest(finale.EXPRPLAYSTART_POSINMEASURE, "EXPRPLAYSTART_POSINMEASURE", 0)
end

-- Test the constants:
TestConstants_EXPRPLAYSTART_()
